#!/usr/bin/env ruby

require 'octokit'
require 'json'

GITHUB_AUTH_TOKEN = `git config com.bohemiancoding.qa.token`.strip
ISSUES_PER_PAGE = 2000
USERNAME = `git config github.user`.strip

client = Octokit::Client.new(:access_token => GITHUB_AUTH_TOKEN)

file = File.read('plugins.json')
json_data = JSON.parse(file)

total_plugin_count = 0

json_data.each do |plugin|
  repo_name = plugin['owner'] + '/' + plugin['name']
  # puts repo_name
  total_plugin_count += 1

  puts
  puts repo_name
  begin
    repo = client.repo(repo_name)
    puts "-------------------------------------------------------------------"
    puts "Stars:       #{repo.stargazers_count}"
    puts "Last push:   #{repo.pushed_at}"
    # puts "Last update: #{repo.updated_at}"
    puts "Open issues: #{repo.open_issues_count}"
  rescue
    puts "Plugin has no repo."
  end
  # #<Set: {:id, :name, :full_name, :owner, :private, :html_url, :description, :fork, :url, :forks_url, :keys_url, :collaborators_url, :teams_url, :hooks_url, :issue_events_url, :events_url, :assignees_url, :branches_url, :tags_url, :blobs_url, :git_tags_url, :git_refs_url, :trees_url, :statuses_url, :languages_url, :stargazers_url, :contributors_url, :subscribers_url, :subscription_url, :commits_url, :git_commits_url, :comments_url, :issue_comment_url, :contents_url, :compare_url, :merges_url, :archive_url, :downloads_url, :issues_url, :pulls_url, :milestones_url, :notifications_url, :labels_url, :releases_url, :deployments_url, :created_at, :updated_at, :pushed_at, :git_url, :ssh_url, :clone_url, :svn_url, :homepage, :size, :stargazers_count, :watchers_count, :language, :has_issues, :has_downloads, :has_wiki, :has_pages, :forks_count, :mirror_url, :open_issues_count, :forks, :open_issues, :watchers, :default_branch, :permissions, :network_count, :subscribers_count}>
end

puts
puts "#{total_plugin_count} plugins"
