name: Update README
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - plugins.json
  workflow_run:
    workflows: ["Update lastUpdated"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Update README
      run: rake readme
    - name: push
      run: |
        git config --global user.name 'Sketch Developer'
        git config --global user.email 'developer@sketch.com'
        git add README.md
        git commit -am 'Update README'
        git push
